### ISSUE TITLE
Arc plots with interaction data requires a ct file

### ISSUE THREAD

**Issue by jwaldern** [Weeks-UNC/RNAvigate#11]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In [5], line 12
      1 noCT = MaP.Sample(sample = "noCT",
      2                  #log =
      3                  #profile =
   (...)
      9                  #pdb_kwargs = 
     10                 )
---> 12 plot2=noCT.plot_arcs(interactions="shapejump")
     13 plot2.axes[0,0].set_ylim(-noCT.data["shapejump"].length/2, noCT.data["shapejump"].length/2)
     14 plot2.axes[0,0].set_aspect("auto")

File ~/Documents/Jupyter/RNAvigate/rnavigate/rnavigate.py:508, in Sample.plot_arcs(self, dance, **kwargs)
    505     plot = plot_arcs_multisample(samples=self.dance,
    506                                  prefiltered=True, **kwargs)
    507     return plot
--> 508 return plot_arcs_multisample([self], **kwargs)

File ~/Documents/Jupyter/RNAvigate/rnavigate/rnavigate.py:651, in plot_arcs_multisample(samples, ct, comp, interactions, interactions_filter, interactions2, interactions2_filter, profile, annotations, labels, region, plot_kwargs, prefiltered, **kwargs)
    645 def plot_arcs_multisample(samples, ct="ct", comp=None,
    646                           interactions=None, interactions_filter={},
    647                           interactions2=None, interactions2_filter={},
    648                           profile="profile", annotations=[], labels=None,
    649                           region="all", plot_kwargs={}, prefiltered=False,
    650                           **kwargs):
--> 651     plot = AP(num_samples=len(samples), nt_length=samples[0].data[ct].length,
    652               region=region, **plot_kwargs)
    653     if labels is None:
    654         labels = ["labels"]*len(samples)

KeyError: 'ct'

**Comment by Psirving** [comment]
Thanks for reporting this Justin. I've been aware of this, but haven't had time to fix it yet. For your purposes, this should work:

```plot2 = noCT.plot_arcs(ct="shapejump")```

In this particular case, Interactions data can stand in for the CT data. You won't be able to use interactions_filter, but I can show you how to get around this.

**Comment by Psirving** [comment]
The new_features branch includes a better solution to this problem. This way you can still apply your filters to the SHAPE-Jump data.
```python
plot2 = noCT.plot_arcs(seq_source="shapejump", ct=None, interactions="shapejump")
```
