### ISSUE TITLE
plot_circle requires a profile to assign color; problem for JuMP data

### ISSUE THREAD

**Issue by jwaldern** [Weeks-UNC/RNAvigate#12]
Attempting to plot ShapeJump interactions in a circular layout, rather than as an Arc Plot. Since shapejump data does not generate a profile, the function can't find the color and fails. See below:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [23], line 2
      1 #Plotting WTT-RT1 as a circ; subtracted background
----> 2 plot_c1 = WT_RT1_norm.plot_circle(
      3     ct="ct",
      4     interactions="shapejump",
      5     interactions_filter={"Percentile_ge":0.95})

File ~/Documents/Jupyter/RNAvigate/rnavigate/rnavigate.py:488, in Sample.plot_circle(self, **kwargs)
    487 def plot_circle(self, **kwargs):
--> 488     return plot_circle_multisample([self], **kwargs)

File ~/Documents/Jupyter/RNAvigate/rnavigate/rnavigate.py:736, in plot_circle_multisample(samples, ct, comp, interactions, interactions_filter, interactions2, interactions2_filter, profile, label, **kwargs)
    733     if interactions2 is not None:
    734         sample.filter_interactions(interactions2, ct,
    735                                    **interactions2_filter)
--> 736     plot.add_sample(sample, ct=ct, comp=comp, interactions=interactions,
    737                     interactions2=interactions2, profile=profile,
    738                     label=label, **kwargs)
    739 return plot

File ~/Documents/Jupyter/RNAvigate/rnavigate/plots/plots.py:36, in Plot.add_sample(self, sample, **kwargs)
     34     if key not in self.pass_through:
     35         kwargs[key] = sample.get_data_list(kwargs[key])
---> 36 self.plot_data(**kwargs)

File ~/Documents/Jupyter/RNAvigate/rnavigate/plots/circle.py:47, in Circle.plot_data(self, ct, comp, interactions, interactions2, profile, label)
     44 # self.add_sequence(ax, ct.sequence, yvalue=0.5)
     45 # self.plot_profile(ax, profile, ct)
     46 ax.set_title(label)
---> 47 nuc_colors = profile.get_colors("profile", profile=profile)
     48 ax.scatter(self.x, self.y, marker='o', c=nuc_colors)
     49 self.i += 1

AttributeError: 'NoneType' object has no attribute 'get_colors'

**Comment by Psirving** [comment]
I wrote this part badly. I will prioritize fixing this. For now though, the only way around it is to give your sample a fake profile.

```
WT_RT1_norm.set_data(
    name="profile",
    instantiator=rnav.data.Profile,
    seq_source="shapejump",
    colors=['black']*WT1_RT1_norm.data["shapejump"].length)
```

Let me know if this works.

**Comment by jwaldern** [comment]
This almost works

 NameError: name ‘rnav’ is not defined

Swapping rnav for MaP (imported rnavigate as MaP) provides a different error:


[cid:B7D475F8-6D35-451A-B666-B5135C3FAF82]

On Oct 25, 2022, at 3:25 PM, Patrick Irving ***@***.******@***.***>> wrote:



I wrote this part badly. I will prioritize fixing this. For now though, the only way around it is to give your sample a fake profile.

WT_RT1_norm.set_data(
    name="profile",
    instantiator=rnav.data.Profile,
    seq_source="shapejump",
    colors=['black']*WT1_RT1_norm.data["shapejump"].length)


Let me know if this works.

**Comment by Psirving** [comment]
Yeah, that was close.

The first error: `NameError: name ‘rnav’ is not defined` likely happened because you forgot to run the cell containing `import rnavigate as rnav`.

The second error: We're trying to create a `Profile` using no data and the bare minimum arguments, but I forgot to add `cmap`. Try this:

```
WT_RT1_norm.set_data(
    name="profile",
    instantiator=rnav.data.Profile,
    seq_source="shapejump",
    cmap="black"
    colors=["black"]*WT1_RT1_norm.data["shapejump"].length)
```

**Comment by Psirving** [comment]
Added some of your requested features in the latest commit. Let me know how it works for you. These were all very useful suggestions, and RNAvigate is better for it.
1. The `primers` annotation, which is basically the same as `spans`, but they are directional. This works with other plot types as well.
2. Circle plots can display annotations.
3. Circle plots accept the argument `seq_source`. This makes it even more flexible than other plot types. I'll probably be adding this feature to all plots in the future. Including the ability to put in any sequence you want here (e.g. aligning the data to the sequence with or without introns).
4. Circle plots use the same color options as secondary structure diagrams: `colors` defines the nucleotide coloring scheme. This was previously taken from profile, so you don't need a profile anymore. `apply_color_to` can be `"sequence"` or `"background"`.

```
import rnavigate as rnav
example = rnav.Sample(
    sample="example",
    shapejump={
        "filepath": "data/example-rnasep-deletions.txt",
        "fasta": "data/RNaseP-noSC.fasta"},
    primers={
        "seq_source": "shapejump",
        "primer_list": [[1,15], [240, 225]],
        "color": "red",
    },
    spans={
        "seq_source": "shapejump",
        "span_list": [[40, 80], [120, 160]],
        "color": "red"})

plot = example.plot_circle(
    seq_source='shapejump',
    interactions="shapejump",
    interactions_filter={
        "Percentile_ge":0.95
    },
    colorbar=False,
    annotations=["primers", "spans"])
plot.save('circle-test.svg')
```
![circle-test](https://user-images.githubusercontent.com/1638005/199560909-b210cc5d-ceb3-41db-88dc-0aac86c27536.svg)
