### ISSUE TITLE
Circ plots do not display with large sequence 

### ISSUE THREAD

**Issue by jwaldern** [Weeks-UNC/RNAvigate#13]
Circ plots do not display, however they save fine.

```
circ_plot = WT.plot_circle(
    ct="ct",
    profile="shapemap",
)

```

Additionally, arcs crossover in the circle plot (see attached). 

<img width="1375" alt="Screen Shot 2022-11-15 at 10 53 00 AM" src="https://user-images.githubusercontent.com/82057741/201971486-371db642-eede-42b1-8728-74481bf8eed8.png">

**Comment by jwaldern** [comment]
Interestingly, plots with less arcs are displayed. 

<img width="1768" alt="less_data" src="https://user-images.githubusercontent.com/82057741/201996449-b8ce636e-ad97-428e-b5f7-8b085adf2631.png">

**Comment by Psirving** [comment]
The issue with arcs crossing when they span the 3' to 5' gap has been fixed in the new_features branch, which will be merged into the main branch soon.

I'm not sure why it isn't displaying inline. It sounds like it could be an issue with either matplotlib or Jupyter and the complexity of the plot.

**Comment by Psirving** [comment]
You could try setting the DPI lower to see if it is an issue with the size of the plot.
```python
circ_plot = WT.plot_circle(
    ct="ct",
    profile="shapemap",
)
circ_plot.fig.set_dpi(100)
```
