### ISSUE TITLE
Does not accept .VARNA structure drawings from VARNA 3.9

### ISSUE THREAD

**Issue by scottallen877** [Weeks-UNC/RNAvigate#16]
I have .VARNA session files from VARNA 3.9 and RNAvigate will not accept them as "ss" input. It produces the following error: 

KeyError                                  Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 #Minigene
----> 2 Unforced_4th_Fold = rnav.Sample(
      3     sample = "Unforced, 4th structure, with DMS, E = -66.5",
      4     dmsmap = "DATA/sample.txt",
      5     ss = "DATA/sample.VARNA",
      6 )
      8 #sample2
      9 sample2 = rnav.Sample(
     10     sample = "s2",
     11     ss = "DATA/s2.VARNA",
     12 )

File /proj/kweeks/bin/RNAvigate/rnavigate/rnavigate.py:317, in Sample.__init__(self, sample, inherit, pdb, ct, compct, ss, fasta, log, shapemap, dmsmap, dancemap, rnpmap, ringmap, shapejump, pairmap, allcorrs, pairprob, allpossible, dance_prefix, annotations)
    315 if None not in [kwargs["filepath"], kwargs["seq_source"]]:
    316     kwargs.update(kwargs.pop("kwargs", {}))
--> 317     self.set_data(name=name, **kwargs)

File /proj/kweeks/bin/RNAvigate/rnavigate/rnavigate.py:371, in Sample.set_data(self, name, filepath, instantiator, seq_source, **kwargs)
    365 self.inputs[name] = {
    366     "filepath": filepath,
    367     "instantiator": instantiator,
    368     "seq_source": seq_source,
    369     "kwargs": kwargs}
    370 # instantiate the data class and add to self.data dictionary
--> 371 self.data[name] = instantiator(filepath=filepath, **kwargs)
    372 # set as default profile if appropriate
    373 if name in self.default_profiles and "profile" not in self.data:

File /proj/kweeks/bin/RNAvigate/rnavigate/data/ct.py:24, in get_ss_class(filepath, **kwargs)
     22     return None
     23 extension = filepath.split('.')[-1]
---> 24 instantiator = {
     25     "varna": VARNA,
     26     "xrna": XRNA,
     27     "nsd": NSD,
     28     "cte": CTE,
     29     "ct": CT,
     30     "dbn": DotBracket,
     31     "bracket": DotBracket,
     32     "json": JSON,
     33 }[extension]
     34 return instantiator(filepath=filepath, **kwargs)

KeyError: 'VARNA'

**Comment by Psirving** [comment]
I’ll fix this. It should work if you rename to lowercase .varna

**Comment by Psirving** [comment]
Try this:
sample.data[“ss”].ycoordinates *= -1
