### ISSUE TITLE
QC plot margins cut off plot elements on exported images

### ISSUE THREAD

**Issue by scottallen877** [Weeks-UNC/RNAvigate#17]
With the new updates, the rnav.plot_qc() plots are not spaced properly and run into one another. Also, when saving images through the matplotlib savefig command, the axis labels are frequently cut off in the exported image despite displaying correctly in RNAvigate Jupyter notebook in the OnDemand portal.

**Comment by Psirving** [comment]
Thanks Scott! I will try to fix this soonish (like sometime this Summer). I'll let you know here.

Quick fixes:
1. If you just need it for a Powerpoint, you can drag and drop the image directly from Jupyter into Powerpoint.
2. If you need it for a figure, you can load the svg into Illustrator. Even though the artboard cuts off the labels, the vectors should still be there in the margins. Select all, scale down the vectors, and it should all fit. Another known issue is that in inches units, the figures are very large, even for a poster. You should scale it down first, then copy into a poster or paper figure.

**Comment by Psirving** [comment]
I've increased the size of the left margin so that everything fits. Thanks Scott!
