### ISSUE TITLE
Specifying a region for "plot_arcs_compare" returns Value error

### ISSUE THREAD

**Issue by bmunn99** [Weeks-UNC/RNAvigate#18]
I've imported rnavigate and my sample data as such:
`import rnavigate as rnav`

`AGO3_WT = rnav.Sample()`
`AGO3_P1 = rnav.Sample()`

When I try to run plot_arcs_compare, it returns this error:

`WT_P1 = rnav.plot_arcs_compare(samples=[AGO3_WT, AGO3_P1],
                              region=[1269, 1769])`

ValueError                                Traceback (most recent call last)
Cell In[23], line 2
      1 # Make an arc diagram comparison
----> 2 WT_P1 = rnav.plot_arcs_compare(samples=[AGO3_WT, AGO3_P1],
      3                               region=[1269, 1769])

File /opt/ohpc/pub/Software/source/RNAvigate/rnavigate/rnavigate.py:1266, in plot_arcs_compare(samples, seq_source, ct, comp, interactions, interactions_filter, interactions2, interactions2_filter, profile, labels, region, plot_kwargs, colorbar, **kwargs)
   1264     plot_kwargs = {}
   1265 if region != "all":
-> 1266     al1 = [i for i, nt in seq1_full.sequence if nt != '.']
   1267     region = [al1[region[0]], al1[region[1]]]
   1268 # coerce interactions and interactions_filter into filters format

File /opt/ohpc/pub/Software/source/RNAvigate/rnavigate/rnavigate.py:1266, in <listcomp>(.0)
   1264     plot_kwargs = {}
   1265 if region != "all":
-> 1266     al1 = [i for i, nt in seq1_full.sequence if nt != '.']
   1267     region = [al1[region[0]], al1[region[1]]]
   1268 # coerce interactions and interactions_filter into filters format

ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Psirving** [comment]
Thank you for catching and reporting this bug! I will be sure to fix it in the next update.

You have a few options for a quick fix:
1) Fix the bug manually by replacing line 1266 in rnavigate/rnavigate.py with the following:
    ```python
    al1 = [i for i, nt in enumerate(seq1_full.sequence) if nt != '.']
    ```
2) Plot the full sequence and zoom in.
3) Use the plot_arcs function and add the second sample using some currently undocumented functions.
    ```python
    WT_P1 = rnav.plot_arcs(samples=[AGO3_WT], region=[1269, 1769])
    rnav.fit_data_list([AGO3_P1.data['ct']], AGO3_WT.data['ct'])
    WT_P1.add_patches(
        ax=WT_P1.axes[0, 0],
        data=AGO3_P1.data['ct'],
        panel='bottom',
        annotation_gap=2)
    ```

**Comment by bmunn99** [comment]
Thanks for the feedback, I tried the third option and it returned this:
TypeError                                 Traceback (most recent call last)
Cell In[8], line 2
      1 WT_P1 = rnav.plot_arcs(samples=[AGO3_WT], region=[1269, 1769])
----> 2 rnav.fit_data_list([AGO3_P1.data['ct']], AGO3_WT.data['ct'])
      3 WT_P1.add_patches(
      4     ax=WT_P1.axes[0, 0],
      5     data=AGO3_P1.data['ct'],
      6     panel='bottom',
      7     annotation_gap=2)

TypeError: fit_data_list() missing 1 required positional argument: 'fit_to'
