### ISSUE TITLE
Pairprob base coloring

### ISSUE THREAD

**Issue by bmunn99** [Weeks-UNC/RNAvigate#19]
Is there a way to filter the interactions = 'pairprob' to display only probabilities > 0.5? Or any sort of filter for that?

**Comment by Psirving** [comment]
Yes there is! Add the interactions_filter argument to your plotting function.
```python
rnav.plot_arcs(
    samples=your_sample_list,
    interactions='pairprob',
    interactions_filter={'Probability_ge': 0.5}
)
```
"Probability" refers to the dataframe column name.
"ge" here means "greater than or equal to". Other operators you can use here are "gt" (greater than), "eq" (equal to), "lt" (less than), "le" (less or equal to), "ne" (not equal to).
