### ISSUE TITLE
DeltaSHAPE does not work when comparing sequences with deletions

### ISSUE THREAD

**Issue by jwaldern** [Weeks-UNC/RNAvigate#21]
When I compare a sequence to itself, DeltaSHAPE produces a plot properly.
Comparing two replicates of the same sequence also produces a plot. 
Comparing two constructs where one has a deletion that the other does not produces the error.

`WT_vs_dp = rnav.analysis.DeltaSHAPE(WT_m, dp_m).plot()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/Users/jwaldern/Documents/Jupyter/2023-07-03_QC_Merged_data_Analysis/2023-08-30_Replicate_comparisons_exons_WT34.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/jwaldern/Documents/Jupyter/2023-07-03_QC_Merged_data_Analysis/2023-08-30_Replicate_comparisons_exons_WT34.ipynb) Cell 82 line 1
----> [1](vscode-notebook-cell:/Users/jwaldern/Documents/Jupyter/2023-07-03_QC_Merged_data_Analysis/2023-08-30_Replicate_comparisons_exons_WT34.ipynb#Y150sZmlsZQ%3D%3D?line=0) WT_vs_dp = rnav.analysis.DeltaSHAPE(WT_m, dp_m).plot()

File [~/RNAvigate/rnavigate/analysis/deltashape.py:56](https://file+.vscode-resource.vscode-cdn.net/Users/jwaldern/Documents/Jupyter/2023-07-03_QC_Merged_data_Analysis/~/RNAvigate/rnavigate/analysis/deltashape.py:56), in DeltaSHAPE.__init__(self, sample1, sample2, pad, mask_5, mask_3, z_coeff, z_thresh, ss_thresh, find_site)
     54 sample1 = sample1.get_data_list("profile").data[columns].copy()
     55 sample2 = sample2.get_data_list("profile").data[columns].copy()
---> 56 assert all(sample1["Sequence"] == sample2["Sequence"]
     57            ), "Sequences don't match"
     58 self.data = sample1.merge(sample2, how="left",
     59                           on=["Nucleotide", "Sequence"],
     60                           suffixes=("_1", "_2"))
     62 # STEP TWO
     63 # smooth data and errors

File [~/opt/anaconda3/envs/RNAvigate/lib/python3.9/site-packages/pandas/core/ops/common.py:65](https://file+.vscode-resource.vscode-cdn.net/Users/jwaldern/Documents/Jupyter/2023-07-03_QC_Merged_data_Analysis/~/opt/anaconda3/envs/RNAvigate/lib/python3.9/site-packages/pandas/core/ops/common.py:65), in _unpack_zerodim_and_defer.<locals>.new_method(self, other)
     61             return NotImplemented
     63 other = item_from_zerodim(other)
---> 65 return method(self, other)

File [~/opt/anaconda3/envs/RNAvigate/lib/python3.9/site-packages/pandas/core/arraylike.py:29](https://file+.vscode-resource.vscode-cdn.net/Users/jwaldern/Documents/Jupyter/2023-07-03_QC_Merged_data_Analysis/~/opt/anaconda3/envs/RNAvigate/lib/python3.9/site-packages/pandas/core/arraylike.py:29), in OpsMixin.__eq__(self, other)
     27 @unpack_zerodim_and_defer("__eq__")
     28 def __eq__(self, other):
---> 29     return self._cmp_method(other, operator.eq)
...
-> 4973     raise ValueError("Can only compare identically-labeled Series objects")
   4975 lvalues = extract_array(self, extract_numpy=True)
   4976 rvalues = extract_array(other, extract_numpy=True)

ValueError: Can only compare identically-labeled Series objects

Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?a62517b9-05e6-492d-b101-797da9717eb5) or open in a [text editor](command:workbench.action.openLargeOutput?a62517b9-05e6-492d-b101-797da9717eb5). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
`

**Comment by Psirving** [comment]
Hi Justin, I forgot about this. Hopefully I told you in person already; this issue was fixed a few months ago.
