### ISSUE TITLE
Not showing sequence and bar plots with region argument when region start < 1

### ISSUE THREAD

**Issue by SimonFelder** [Weeks-UNC/RNAvigate#30]
When entering a region that does not start with 1, the plots look wrong but it is very hard to troubleshoot.

**Comment by Psirving** [comment]
Thanks Simon,

My memory of this from troubleshooting with you last week is that no Error is produced, but that the sequence and bar plots are not displayed. Arcs and annotations are unaffected. Is that accurate?

**Comment by SimonFelder** [comment]
Right, sequence, profile and skyline plots disappear.

![Untitled](https://github.com/Weeks-UNC/RNAvigate/assets/115376815/e1c405c4-9ec5-4b52-afb0-4584f5a9045f)

**Comment by Psirving** [comment]
Additional notes:
- region start >= 1 works fine
- region start < 1 results in this unexpected behavior
- start and end must be:
  - integers
  - between 1 and length of sequence, inclusive
  - end > start

**Comment by Psirving** [comment]
This has been fixed in the master branch. `region` must follow these rules or an error is thrown:
- start >= 1
- start < end < RNA length
- start and end are integers
