### ISSUE TITLE
Tiny Secondary structures get squished

### ISSUE THREAD

**Issue by VonBoss** [Weeks-UNC/RNAvigate#4]
Small secondary structures are compressed. This has to do with default padding in the figures. 
![6VA4_clean_2D](https://user-images.githubusercontent.com/10247744/186744962-bfed63fa-acab-42d0-849b-97f7482a1a5f.png)

**Comment by Psirving** [comment]
This has been fixed in the main branch. All plots now have much more consistent axes unit to inches ratios.
