### ISSUE TITLE
arc plots for long transcripts (>3500 bases) crash program

### ISSUE THREAD

**Issue by scottallen877** [Weeks-UNC/RNAvigate#6]
For Longleaf install using Jupyter notebook (UNC OnDemand interface). Trying to generate an arc plot for a 7kb transcript crashes the program. Generating arc plots for regions <=3500 bases is successful. Generating simpler plots for the full 7kb transcript completes without error.

Error message generated for larger transcripts:
"Kernel Restarting
The kernel for [Notebook name].ipynb appears to have died. It will restart automatically."

Examples:
Generates above error
`plot = DMS.plot_arcs(interactions="pairprob")`
Generates above error
`plot = DMS.plot_arcs(interactions="pairprob", region=[1,5000])`
Generates above error
`plot = DMS.plot_arcs(interactions="pairprob", region=[1,4000])`
Completes without error
`plot = DMS.plot_arcs(interactions="pairprob", region=[1,3500])`
Completes without error
`plot = DMS.plot_arcs(interactions="pairprob", region=[1,3000])`
Completes without error for full 7kb transcript
`plot = DMS.plot_shapemapper()`

**Comment by Psirving** [comment]
Man, Scott. You're really testing RNAvigates limits. Awesome!

I suspect you are running up against OnDemand's default memory allocation. Try requesting more memory.

Additionally, by default all plots are stored in memory. Run the following to clean up if making a lot of large plots:
```python
import matplotlib.pyplot as plt
plt.close('all')
```

There is another limit on plot size imposed by matplotlib, which you won't be able to overcome. I'm not sure if a 7kb RNA will reach that limit or not.

**Comment by scottallen877** [comment]
Hey Patrick - that totally worked. Using more memory allowed generating the full length arc plot without error. I'll post the solution here in case other lab members run into this in the future:

When generating the Jupyter notebook session in the OnDemand Portal there is a box for additional arguments. 
Enter: `--mem=8G` corresponding to 8GB. More or less may be necessary depending on transcript length.
