### ISSUE TITLE
Removing complimentary PAIRS from arcplots

### ISSUE THREAD

**Issue by jwinstonarney** [Weeks-UNC/RNAvigate#7]
By default, plotting pairmap data on an arcplot shows primary, secondary, and complimentary PAIRs. In principle, complimentary (gray) PAIRS should only be enabled by the {"all_pairs": True} interaction filter. Adding a {"all_pairs": False} filter doesn't remove the complimentary PAIRS.
![Screen Shot 2022-09-29 at 12 16 39 PM](https://user-images.githubusercontent.com/60202188/193084573-6fd8b269-e413-4d0e-8e68-74ee01d0cde7.png)

**Comment by Psirving** [comment]
I just pushed changes that resolve this issue and the lowercase "t" issue. I also updated RNAvigate on longleaf. All you need to do is reload your notebook.
