### ISSUE TITLE
Error when loading shapemap profiles for skyline array plots

### ISSUE THREAD

**Issue by davidqiu54** [Weeks-UNC/RNAvigate#8]
![image](https://user-images.githubusercontent.com/54602098/193088985-366c4a7a-692e-44af-8380-bfa050b14b42.png)

leads to keyword error "Norm_profile". Unsure if syntax issue or actual bug.

**Comment by Psirving** [comment]
Please send the error traceback and attach the _profile.txt file. My guess is that your file is not in standard Shapemapper format.

**Comment by davidqiu54** [comment]
KeyError                                  Traceback (most recent call last)
~/.conda/envs/mapexplors/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Norm_profile'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-5-e39ef894fc3d> in <module>
      5     return kwargs
      6 
----> 7 samples = [MaP.Sample(**kwargs(n)) for n in ["TMO", "DMS"]]

<ipython-input-5-e39ef894fc3d> in <listcomp>(.0)
      5     return kwargs
      6 
----> 7 samples = [MaP.Sample(**kwargs(n)) for n in ["TMO", "DMS"]]

~/JNBTools/rnavigate/rnavigate.py in __init__(self, sample, pdb, ct, compct, ss, fasta, log, shapemap, dmsmap, dancemap, rnpmap, ringmap, shapejump, pairmap, allcorrs, pairprob, dance_prefix, sites, spans, groups, orfs, motif)
    244                 # additional_kwargs = kwargs.pop("kwargs", {})
    245                 kwargs.update(kwargs.pop("kwargs", {}))
--> 246                 self.set_data(name=input, **kwargs)
    247 
    248     def set_data(self, name, filepath=None, instantiator=None, seq_source=None,

~/JNBTools/rnavigate/rnavigate.py in set_data(self, name, filepath, instantiator, seq_source, **kwargs)
    266             "seq_source": seq_source,
    267             "kwargs": kwargs}
--> 268         self.data[name] = instantiator(filepath=filepath, **kwargs)
    269         if name in self.default_profiles and "profile" not in self.data:
    270             self.data["profile"] = self.data[name]

~/JNBTools/rnavigate/data/profile.py in __init__(self, filepath, dms, datatype, read_csv_kw, **kwargs)
     88                                      "Norm_stderr", "Sequence"],
     89                            "na_values": "-999"}
---> 90         super().__init__(filepath=filepath,
     91                          datatype=datatype,
     92                          sep="\t",

~/JNBTools/rnavigate/data/profile.py in __init__(self, datatype, column, ap_scale_factor, dataframe, sequence, fasta, filepath, sep, read_csv_kw, cmap, norm_method, norm_values, color_column, colors)
     39             self.colors = self.data["Colors"]
     40         else:
---> 41             self.set_profile_colors(start_from="defaults")
     42 
     43     def read_file(self, filepath, sep, read_csv_kw):

~/JNBTools/rnavigate/data/profile.py in set_profile_colors(self, start_from, **kwargs)
     76         elif cv["norm_method"] is None:
     77             def norm(x): return x  # does nothing to values
---> 78         values = self.data[cv["column"]].values
     79         values = norm(values)
     80         self.colors = cv["cmap"](values)

~/.conda/envs/mapexplors/lib/python3.9/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~/.conda/envs/mapexplors/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'Norm_profile'


I've checked the profile file, there's no norm_profile column. I believe that's the issue. My guess is that none of the nucleotides had enough read depths to generate a norm_profile so shapemapper didn't include them. What's confusing is that I've checked some previous profiles I've loaded into RNavigate and they didn't have norm_profile either, but still worked. Now with the new version they don't work.

**Comment by Psirving** [comment]
First, the intended fix for this is to run Shapemapper with the minimum depth threshold set to something that makes sense for your data. Then RNAvigate will behave well. I think I actually want RNAvigate to fail in this case, because most of the functionality of "shapemap" data is based on this column. I will give it a more helpful error message. Alternatively, I could ignore this issue and print a warning for users that this data will cause errors with most plots (except skyline).

You could get around this by using the set_data() function. This is the intended method for custom data, and I'll be adding it to the docs sometime soon.

```python
sample_names = ["TMO", "DMS"]
samples = []
for sample in sample_names:
    current_sample = rnav.Sample(sample=sample)
    current_sample.set_data(
        name="shapemap",
        filepath=f"{path}DCAF10_{sample}_profile.txt",
        instantiator=rnav.data.Profile,
        seq_source="self",
        column="Reactivity_profile",
        color_column="Reactivity_profile",
        ap_scale_factor=20,
        cmap="viridis", # viridis is an mpl colormap, it might not look good for your data, you'll have to decide.
        norm_method="min_max",
        norm_values=[0, 0.2])
    samples.append(current_sample)
```

**Comment by davidqiu54** [comment]
I think the custom data loading is fine, a more helpful error message would be good though. I think this issue is resolved.
